name: check-action
on:
  push:
    branches:
      - exercise_02
  pull_request:
    branches:
      - exercise_02
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install deps
        run: npm ci
      - name: test
        run: npm run test